### ISSUE TITLE
Complete project

### ISSUE THREAD

**Issue by Glaycow** [TemainfoSoftware/truly-ui#257]
Seria interessante ter como baixar um repositório completo com tudo configurado.

**Comment by abalad** [comment]
We are developing functionality to add the project and its settings using `ng add `command. But for now you can check the operation of Truly in action through the links below.

https://github.com/TemainfoSoftware/truly-ui#quick-links
https://stackblitz.com/edit/truly-ui-simple

And you can download a project already configured through the link:
https://github.com/TemainfoSoftware/truly-ui/tree/master/integration
