### ISSUE TITLE
Switch not moving in straight line. Intentional?

### ISSUE THREAD

**Issue by ottosson** [TemainfoSoftware/truly-ui#290]
**Describe the bug**
When toggling the switch component on/off the "indicator" circle is not moving in a straight line from right to left, it slightly moves downward first and then comes back to the center.

![switch_glitch_slow](https://user-images.githubusercontent.com/3355320/56742947-faea3b80-6775-11e9-9668-a498796dd069.gif)

I'm not sure if this is intentional, but I would prefer it to go in a straight line.

**Desktop (please complete the following information):**
WIndows 10
Firefox, same in other browsers as well.

**Comment by WilliamAguera** [comment]
This will be fixed. We are sending a new version tomorrow. It will be available in the new version.
