### ISSUE TITLE
Route changes with tab control

### ISSUE THREAD

**Issue by ottosson** [TemainfoSoftware/truly-ui#300]
I would like to be able to change routes when using the tab control, similar to the [Angular Material tab control](https://material.angular.io/components/tabs/overview#tabs-and-navigation). Is this something on the road map?

Thanks!

**Comment by WilliamAguera** [comment]
Hello, I would like to thank you for using truly-ui. So as we have in our lib, you can use router outlet's inside of tab's, you can name it on angular routing config.

I made an example for you, check this out: https://stackblitz.com/edit/truly-ui-routing-tabs

**Comment by ottosson** [comment]
Ah! I didn't know you could do that. It works as I wanted it. Big thanks!
