### ISSUE TITLE
Module not found error when importing CoreService

### ISSUE THREAD

**Issue by waltersung** [TemainfoSoftware/truly-ui#317]
Hi
I am trying the sample code for _runtime theme switching_ and I get the following error:
Module not found: Error: Can't resolve 'truly-ui/components/core/services/core.service'

I am using the exact code from the sample in the app.component.
I confirmed the module exists, but for some reason I cannot import it.

**Comment by abalad** [comment]
It was fixed, and already sending a new release with the race.

**Comment by abalad** [comment]
I created an example using the new patched version: 
https://stackblitz.com/edit/truly-ui-simple-gpr6hs?file=src/app/app.component.html

**Comment by waltersung** [comment]
It works!
Thank you
:)
