### ISSUE TITLE
tl-tabcontrol: height in em does not seem to work

### ISSUE THREAD

**Issue by JPGygax68** [TemainfoSoftware/truly-ui#319]
This works:
```html
<tl-tabcontrol [height]="'300px'">
```
but this doesn't:
```html
<tl-tabcontrol [height]="'5em'">
```
i.e., the height stays the same as it would be without a height attribute.

**Comment by abalad** [comment]
@JPGygax68 Could you reproduce the error using the example in StackBlitz?

https://stackblitz.com/edit/truly-ui-simple

**Comment by JPGygax68** [comment]
I can no longer reproduce the problem now, neither on Stackblitz nor in my own project (Electron-based). The only explanation I can think of is a refresh problem.
I'll leave the issue open just a little while longer (I have an alignment problem now between a checkbox and the Submit button - following your example code).
