### ISSUE TITLE
Can't get bootstrap to work correctly on Electron

### ISSUE THREAD

**Issue by JPGygax68** [TemainfoSoftware/truly-ui#320]
I'm working with Electron and am getting:
```
bootstrap.min.js:6 Uncaught TypeError: Cannot read property 'fn' of undefined
    at bootstrap.min.js:6
    at bootstrap.min.js:6
    at bootstrap.min.js:6
```
Two questions here - one, is Bootstrap a requirement for working with truly-ui, and two, does truly-ui use jquery?

**Comment by abalad** [comment]
@JPGygax68 Apparently this error is occurring in the `bootstrap`, Truly-UI because actually being developed thinking `DESKTOP `applications it does not have Jquery as part of its CORE.

Truly-UI Also does not need the dependency of Bootstrap it has its own UI and working components independent of any other UI Framework.

**Comment by abalad** [comment]
About your error is a known error when using JQUERY together with ELECTRON, which is why we created our Framework independent of others.

Take a look at this Tread:
https://stackoverflow.com/questions/50541298/uncaught-typeerror-cannot-read-property-fn-of-undefined-electron-2-angular

**Comment by JPGygax68** [comment]
Thank you! I was afraid Bootstrap was needed because you apparently are using it in your examples (`div class="form-group">...`. I'm glad, I much prefer not having to add either jQuery or Bootstrap.

**Comment by abalad** [comment]
We are updating our documentation just to remove this dependency from our Showcase. But the Framework itself does not have this dependency.

Soon we will make the new documentation much more practical and with more real examples.
