### ISSUE TITLE
Question: can I make a tl-button inline?

### ISSUE THREAD

**Issue by JPGygax68** [TemainfoSoftware/truly-ui#322]
I'd like to have a text field immediately followed by an "open folder" button (i.e., a file/folder picker). But the div element created by tl-button has `display: block`. What would you recommend?

EDIT: I noticed that tl-input puts the actual input field into a table-div as a table-cell.  Is there a way to sneak an additional component into that table-div?

**Comment by abalad** [comment]
You can use the `textAfter` property of tl-input and `clickAddon` event as well:  

Check this out:  https://stackblitz.com/edit/truly-ui-simple-e6jr4y

**Comment by JPGygax68** [comment]
Thank you! Can I create an icon button too?

**Comment by abalad** [comment]
But then you will have to use the property  `[iconBefore]`  or ` [iconAfter] `
You can check this example and others in the documentation: http://truly-ui.com/input
Ex. 
```html 
<tl-input [iconBefore] = "'ion ion-card'" [iconAfter] = "'ion ion-social-usd'"> </ tl-input>
```

**Comment by JPGygax68** [comment]
Works perfectly, thanks again! I'm sorry, that was in the docs, I don't know how I missed it.
