### ISSUE TITLE
Cannot import Truly UI component

### ISSUE THREAD

**Issue by JPGygax68** [TemainfoSoftware/truly-ui#323]
I needed to  access a Truly-UI component from my component code, and did this:
```typescript
@ViewChild('browsingPanel') private browsingPanel: TlOverlayPanel;
```
VSCode generated the following import statement for me:
```typescript
import { TlOverlayPanel } from 'truly-ui/components/overlaypanel/overlay-panel';
```
but Angular has a problem with it:
```
Module not found: Error: Can't resolve 'truly-ui/components/overlaypanel/overlay-panel' in 'D:\Training\electron\electron-angular-native\src\app\settings
```
I found no solution online, only the following [tidbit](https://lazydevguy.wordpress.com/2018/01/18/angular-module-import-issue-error-cant-resolve-angular-core-src/) .

(I'm working with Electron v4.2.6)

**Comment by JPGygax68** [comment]
I've experimented on [stackblitz](https://stackblitz.com/edit/truly-ui-simple-e6jr4y?file=src%2Fapp%2Fapp.component.html) and determined that there, it is apparently possible to import `TlOverlayPanel`  directly from `truly-ui` - even though the Stackblitz *editor* underlines the import statements in red! 

This is very strange. Updating Truly UI from 4.1.3 to 4.2.0 did not help either. I see that Stackblitz uses Angular 8 though, while I'm still at 7. I will try upgrading and report again.

**Comment by WilliamAguera** [comment]
This happen because  the class is not exported on lib, but we are fixing this issue, we are aware of it. For now, to do `ViewChild` you just remove the class and it will work as well.

like this: `@ViewChild('browsingPanel') private browsingPanel;`

**Comment by abalad** [comment]
Fixed, install with command `npm install truly-ui@dev --save` until we ship a new version for production with the correction
