### ISSUE TITLE
TypeError: "element[NATIVE_ADD_LISTENER] is not a function"

### ISSUE THREAD

**Issue by JPGygax68** [TemainfoSoftware/truly-ui#325]
I'm seeing this error message in the console when executing one of the samples you helped me with earlier, see this [stackblitz](https://stackblitz.com/edit/truly-ui-simple-7lqc5a).

The example still appears to work, so I'm not sure if or how much of a problem it represents.

I've seen the same error referenced [here](https://mdbootstrap.com/support/angular/mdb-8-mdbbtn-throws-elementnative_add_listener/). I think it might be related to Angular 8.

**Comment by WilliamAguera** [comment]
I think that happens because the `[elementOrigin]` property receive an `HTMLElement`. But when we do a ViewChild angular return an ElementRef and the element itself can be access throught `nativeElement `property of it.

I updated that sample and I hope that fix this error.

**Comment by WilliamAguera** [comment]
https://stackblitz.com/edit/truly-ui-simple-7lqc5a
