### ISSUE TITLE
Datatable columns suggested enhancement

### ISSUE THREAD

**Issue by waltersung** [TemainfoSoftware/truly-ui#332]
Hi

I have a suggestion for the datatable.
I want to use the same table to load different data sets, but the columns can only be set once when the table is created.
It would be nice if there were a way to reset the columns so that a different data set could be loaded in the table.
It would also be great if there was a way to add/remove columns dynamically.

Thank you 
Walter

**Comment by abalad** [comment]
We are looking into creating this feature and soon. If you feel comfortable, you can give us an idea of what you would need and what this implementation would look like.

**Comment by waltersung** [comment]
Hi 
Currently I am just interested in changing the data that I load into the table. The current table does not refresh the columns. It looks like this is not difficult to change in the code, but I don't know what may rely on the current behaviour.
Additionally I would like to choose columns to show and hide or add and remove columns, but this is not as important for me. The column changes do not need to modify the underlying data.
In the future it would also be fantastic if the table was editable and could modify the data, but I do not need this capability at the moment.
W

**Comment by abalad** [comment]
Added feature to change data via TEMPLATE in version 5.0.0
