### ISSUE TITLE
Set selected item in listbox

### ISSUE THREAD

**Issue by waltersung** [TemainfoSoftware/truly-ui#334]
Hi
How can I specify which item in a listbox is selected when loading data?
W

**Comment by WilliamAguera** [comment]
Hi,

You can you use the `select ` method of listbox to do that. I want to remember you that listbox works with infinite scroll, so if the item it's not available on dom it will not work. But we are working to improve this feature and we are working on a new doc to explain all features of the components that are not documentated.


Here's an example to help you:
https://stackblitz.com/edit/listbox-example
