### ISSUE TITLE
Truly-UI semi-unusable (currently)

### ISSUE THREAD

**Issue by JoeWorker** [TemainfoSoftware/truly-ui#353]
Hey guys. This is for any new comers...

But first I want to commend the creators - you've done amazing work to date. I don't choose any UI lightly, and I've come this far, because you're creation looks absolutely stunning.

On the Documentation site.

Which brought me to write this post. That's all that works, seemingly.

From onset, the first "how to install and use" example is buggy.

`   <tl-input
     ngModel="Many Properties"
     [iconBefore]="'ion-printer'"
     [placeholder]="'With Placeholder'"
     [textAfter]="'US'"
     [clearButton]="true"
     [autocomplete]="'off'">
    </tl-input>`

"ion-printer" gives no icon. "ion ion-printer" neither.

Which is fine, you have robust icon support, just use font-awesome with your inputs.

The stackblitz setup only shows a basic input, and toast message.
...and looks like this:
![image](https://user-images.githubusercontent.com/34388266/71321630-fde42a00-24c4-11ea-8368-495778d203ed.png)

While my install requires to remove the ".forRoot()" for Inputs and Toasts...

The "Sample App" link is broken...
![image](https://user-images.githubusercontent.com/34388266/71321646-5a474980-24c5-11ea-80be-ef4d39acf903.png)

The documentation is incomplete:
...take the sidebar (which was one of the main reasons I opted in on starting to using the lib).
![image](https://user-images.githubusercontent.com/34388266/71321674-de013600-24c5-11ea-87f1-48eabb1413c1.png)

Just enough to say nothing.
But wait?
![image](https://user-images.githubusercontent.com/34388266/71321691-0426d600-24c6-11ea-807f-65bb5853dab0.png)

Just enough to be confusing...
Because a day later, you dig into the code and find out that there really is no "toggle()" method on the sidebar container.
![image](https://user-images.githubusercontent.com/34388266/71321705-46e8ae00-24c6-11ea-88d6-2975a1dd34ea.png)

Would love to use the UI... It really is what I'm looking for, at the least for this project I'm starting.
Unfortunately, as it is...it won't suffice. Simply due to the uncertainty of what works and what needs work.

Running the latest ng-cli, yarn, Truly-UI (Dec 2019).

If you need some help with the docs, let me know, I'm open to new projects.

Else, hope this saves someone a day. And I do really hope the UI comes full fledged soon!

It really looks great, and the logic in the usability is great. For the features that work.

Looking forward to more of those!

**Comment by WilliamAguera** [comment]
Thank you for the comments about the lib. We are aware that the docs are not good, we are working on a new one updated. There's a lot of changes every day on the lib but we are struggling with the docs. We're building a new page of docs more clearly to understand that will help it a lot to use. stay tuned.

**Comment by nascarjake** [comment]
Ahhh I want to use this so bad. I've fallen in love with it. 
But It just doesnt work. :(
From what I can tell its not just the docs, though perhaps without the right docs I'm using it incorrectly. But even by looking at the code and running things the way it looks they should be run - I still get errors when doing things like using modal windows. 

With all the crazy virus stuff going on- what does the roadmap look like @WilliamAguera ? 

I have a product I really want to be developing right now using this inside of Electron. Is there any discord channel or anything I could get more updated help at?
Theres really no other component library Ive found that checks all the boxes like this does. Really hope I can use it and I don't have to settle for another library. If theres any recommendations to alternatives in the meantime I'm open to it as a fallback - hope we can figure out how to use this though. <3
