### ISSUE TITLE
Can't get ChatListModule working

### ISSUE THREAD

**Issue by CarlosBC** [TemainfoSoftware/truly-ui#387]
I have added ChatListModule on app.module.ts like all the other modules, but i keep getting the error:
Can't bind to 'user' since it isn't a known property of 'app-chat2'.
1. If 'app-chat2' is an Angular component and it has 'user' input, then verify that it is part of this module.
2. If 'app-chat2' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("  (selectContact)="onSelectContactOne($event)"
           (send)="onSendMessage($event)"
           [ERROR ->][user]="user"
           [contacts]="contacts">
</app-chat2>

MY CODE IS:

// app.module.ts
import { InputModule, ButtonModule, CoreModule, MenuModule, ButtonGroupModule, MultiViewModule, IconsModule, AvatarModule, ChatListModule } from 'truly-ui'; //CoreModule

@NgModule({
  declarations: [
    AppComponent,
    PlayerComponent,
    FooterComponent,
    HeaderComponent,
    PageCategoriesComponent,
    PageChatComponent,
    PageProfileComponent,
    PageHomeComponent,
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    AppRoutingModule,
    HttpClientModule,

    //TrulyUI
    CoreModule.forRoot({theme: 'orange'}), // Configurations
    InputModule,
    ButtonModule,
    MenuModule,
    ButtonGroupModule,
    MultiViewModule,
    IconsModule,
    AvatarModule,
    ChatListModule,
// etc

// page.html
<app-chat2 (readMessage)="onReadOne($event)"
           (selectContact)="onSelectContactOne($event)"
           (send)="onSendMessage($event)"
           [user]="user"
           [contacts]="contacts">
</app-chat2>

// page.component.ts
export class PageChatComponent implements OnInit {
  constructor() { }
  ngOnInit() {
  }
  readMessage(msg:ChatMessage){
  }
  selectContact(contact, unreadMessages){
  }
  send(msg:ChatMessage){
  }
  user:ChatContact={
    id:'1',
    name: 'Name 1',
    description: 'User description',
    status:Status.ONLINE,
    // gravatar?: string;
    // image:'',
  };
  contacts:ChatContact[]=[{
    id:'2',
    name: 'Name 2',
    description: 'Description 2',
    status:Status.ONLINE,
    // gravatar?: string;
    // image:'',
  }];
}

**Comment by WilliamAguera** [comment]
You have to declare your component in order to use 2 chats in the same page, pls, give us an example on stackblitz so we may help you.

**Comment by WilliamAguera** [comment]
closing issue without response
